# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Newton physics assembly for the Franka RJ45 insertion task."""

from .rj45_assembly import (
    CABLE_KINEMATIC_COUNT,
    CABLE_SEGMENT_COUNT,
    GRASP_FRICTION,
    GRASP_PROXY_CENTER,
    GRASP_PROXY_HALF_EXTENTS,
    INSERTION_DISTANCE,
    NEWTON_RJ45_SOURCE_COMMIT,
    RJ45_ASSET_PATH,
    RJ45_ASSET_SHA256,
    RJ45_REFERENCE_SIM_DT,
    RJ45_VBD_CONTACT_BUFFER_SIZE,
    RJ45_VBD_ITERATIONS,
    RJ45_VBD_LEGACY_CONTACT_HARD,
    SUPPORT_PLANE_CONTACT_KD,
    SUPPORT_PLANE_CONTACT_KE,
    SUPPORT_PLANE_CONTACT_KF,
    SUPPORT_PLANE_LOCAL_HEIGHT,
    SUPPORT_PLANE_MU,
    TASK_BODY_COUNT,
    FrankaGraspShapeIds,
    Rj45InsertionDriveCfg,
    Rj45NewtonAssembly,
    Rj45NewtonAssemblyBuilder,
    Rj45WorldBodyIds,
    configure_franka_finger_contact_material,
    rj45_reset_physics_contract,
    resolve_franka_grasp_shape_ids,
    validate_rj45_vbd_solver_cfg,
    verify_rj45_asset,
)

__all__ = [
    "CABLE_KINEMATIC_COUNT",
    "CABLE_SEGMENT_COUNT",
    "GRASP_FRICTION",
    "GRASP_PROXY_CENTER",
    "GRASP_PROXY_HALF_EXTENTS",
    "INSERTION_DISTANCE",
    "NEWTON_RJ45_SOURCE_COMMIT",
    "RJ45_ASSET_PATH",
    "RJ45_ASSET_SHA256",
    "RJ45_REFERENCE_SIM_DT",
    "RJ45_VBD_CONTACT_BUFFER_SIZE",
    "RJ45_VBD_ITERATIONS",
    "RJ45_VBD_LEGACY_CONTACT_HARD",
    "SUPPORT_PLANE_CONTACT_KD",
    "SUPPORT_PLANE_CONTACT_KE",
    "SUPPORT_PLANE_CONTACT_KF",
    "SUPPORT_PLANE_LOCAL_HEIGHT",
    "SUPPORT_PLANE_MU",
    "TASK_BODY_COUNT",
    "FrankaGraspShapeIds",
    "Rj45InsertionDriveCfg",
    "Rj45NewtonAssembly",
    "Rj45NewtonAssemblyBuilder",
    "Rj45WorldBodyIds",
    "configure_franka_finger_contact_material",
    "rj45_reset_physics_contract",
    "resolve_franka_grasp_shape_ids",
    "validate_rj45_vbd_solver_cfg",
    "verify_rj45_asset",
]
